# Generated by Django 3.2.6 on 2021-08-12 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
