# Generated by Django 3.2 on 2021-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_post_post_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_hit',
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
