# Generated by Django 3.2 on 2021-06-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
