# Generated by Django 3.2 on 2021-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='organic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='usual',
            field=models.BooleanField(default=True),
        ),
    ]
