# Generated by Django 3.2.4 on 2021-06-26 06:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('all_nutrition', models.TextField()),
                ('allegy_nutrition', models.TextField()),
                ('Feature', models.CharField(choices=[('Halal 인증', 'Halal 인증'), ('Vegan', 'Vegan'), ('사찰 음식', '사찰 음식')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Market_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('food_name', models.CharField(max_length=50)),
                ('main_picture', models.ImageField(upload_to='image')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(choices=[('master', 'master'), ('user', 'user')], max_length=10)),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('vegan_step', models.CharField(blank=True, choices=[('100% 비건', '100% 비건'), ('일부 비건', '일부 비건')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vegan_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vegan_step', models.CharField(choices=[('100% 비건', '100% 비건'), ('일부 비건', '일부 비건')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('음식점', '음식점'), ('화장품', '화장품'), ('카페', '카페')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Store_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='admin_site.vegan_store')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='admin_site.market_goods')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='admin_site.food')),
            ],
        ),
    ]
