# Generated by Django 3.2.4 on 2021-06-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_review',
            old_name='comment',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='store_review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='admin_site.vegan_store'),
        ),
    ]
