# Generated by Django 3.2.4 on 2021-06-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_review',
            old_name='comment',
            new_name='review',
        ),
    ]
