# Generated by Django 3.2.3 on 2021-06-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_auto_20210626_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Feature',
            field=models.CharField(blank=True, choices=[('Halal 인증', 'Halal 인증'), ('Vegan', 'Vegan'), ('사찰 음식', '사찰 음식')], max_length=10),
        ),
    ]
