# Generated by Django 3.2.4 on 2021-06-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_rename_comment_food_review_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER_CUSTOM_VEGAN_STORE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vegan_step', models.CharField(choices=[('100% 비건', '100% 비건'), ('일부 비건', '일부 비건')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('음식점', '음식점'), ('화장품', '화장품'), ('카페', '카페')], max_length=10)),
            ],
        ),
    ]
