# Generated by Django 3.2.4 on 2021-06-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_user_custom_vegan_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USER_CUSTOM_VEGAN_STORE',
            new_name='User_Custom_Store',
        ),
    ]
