# Generated by Django 3.2.3 on 2021-06-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_alter_food_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market_goods',
            name='main_picture',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_site.market_goods')),
            ],
        ),
    ]
