# Generated by Django 3.2.3 on 2021-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_auto_20210627_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
