# Generated by Django 3.2.4 on 2021-06-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='store_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='reportcontent',
            field=models.TextField(default=''),
        ),
    ]
