# Generated by Django 3.2.4 on 2021-08-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_title', models.CharField(max_length=100)),
                ('add_content', models.TextField(default='')),
                ('image', models.ImageField(blank=True, upload_to='blog')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=100)),
                ('report_content', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='reportcontent',
        ),
    ]
