# Generated by Django 3.2 on 2021-07-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20210702_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vegan',
            field=models.CharField(choices=[('us', 'unselected'), ('vg', 'vegan'), ('lt', 'lacto'), ('ov', 'ovo'), ('lov', 'lacto_ovo'), ('pc', 'pesco'), ('fx', 'flexiterian')], default='unselected', max_length=20),
        ),
    ]
