# Generated by Django 3.2 on 2021-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_vegan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vegan',
            field=models.CharField(max_length=225),
        ),
    ]
