# Generated by Django 3.2 on 2021-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_vegan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vegan',
            field=models.CharField(choices=[('us', 'unselected'), ('vg', 'vegan'), ('lt', 'lacto'), ('ov', 'ovo'), ('lov', 'lacto_ovo'), ('pc', 'pesco'), ('fx', 'flexiterian')], max_length=225),
        ),
    ]
