# Generated by Django 3.2.4 on 2021-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.ManyToManyField(related_name='_detail_category_f1_+', to='detail.Category')),
                ('f2', models.ManyToManyField(related_name='_detail_category_f2_+', to='detail.Category')),
                ('f3', models.ManyToManyField(related_name='_detail_category_f3_+', to='detail.Category')),
                ('f4', models.ManyToManyField(related_name='_detail_category_f4_+', to='detail.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
        migrations.DeleteModel(
            name='Vegan',
        ),
    ]
