# Generated by Django 3.2.4 on 2021-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20210703_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.TextField()),
                ('f2', models.TextField()),
                ('f3', models.TextField()),
                ('f4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.TextField()),
                ('f2', models.TextField()),
                ('f3', models.TextField()),
                ('f4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.TextField()),
                ('f2', models.TextField()),
                ('f3', models.TextField()),
                ('f4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vegan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.TextField()),
                ('f2', models.TextField()),
                ('f3', models.TextField()),
                ('f4', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
