# Generated by Django 3.2.4 on 2021-07-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_auto_20210703_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.TextField(verbose_name='채소류')),
                ('f2', models.TextField(verbose_name='과일류')),
                ('f3', models.TextField(verbose_name='곡류')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.TextField(verbose_name='열량')),
                ('f2', models.TextField(verbose_name='탄수화물')),
                ('f3', models.TextField(verbose_name='단백질')),
                ('f4', models.TextField(verbose_name='지방')),
                ('f5', models.TextField(verbose_name='당류')),
                ('f6', models.TextField(verbose_name='콜레스테롤')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingMall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.TextField(verbose_name='마켓컬리')),
                ('f2', models.TextField(verbose_name='쿠팡')),
                ('f3', models.TextField(verbose_name='푸드슈퍼마켓')),
                ('f4', models.TextField(verbose_name='G마켓')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
        migrations.DeleteModel(
            name='Vegan',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='f1',
            field=models.TextField(verbose_name='나물'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='f2',
            field=models.TextField(verbose_name='생선'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='f3',
            field=models.TextField(verbose_name='떡'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='f4',
            field=models.TextField(verbose_name='면'),
        ),
    ]
