# Generated by Django 3.2.4 on 2021-07-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0005_auto_20210714_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgriculturalProducts',
            new_name='Products',
        ),
    ]
